server:
  port: 8081

spring:
  application:
    name: scheduling-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:9001/eureka}